# Generated by Django 6.0.5 on 2026-05-18 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], max_length=3)),
                ('timestamp_gps', models.DateTimeField()),
                ('timestamp_device', models.DateTimeField()),
                ('sync_received_at', models.DateTimeField(blank=True, null=True)),
                ('gps_lat_smoothed', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_lng_smoothed', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_accuracy_metres', models.IntegerField()),
                ('rssi_avg', models.IntegerField(blank=True, null=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=255)),
                ('wifi_bssid', models.CharField(blank=True, max_length=17)),
                ('wifi_band', models.CharField(choices=[('2.4GHz', '2.4GHz'), ('5GHz', '5GHz'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('biometric_passed', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_synced', models.BooleanField(default=False)),
                ('device_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkin_records', to='devices.devicebinding')),
            ],
            options={
                'db_table': 'checkin_records',
                'constraints': [models.UniqueConstraint(fields=('device_binding', 'timestamp_gps'), name='unique_checkin_per_device_per_timestamp')],
            },
        ),
    ]
