# Generated by Django 6.0.5 on 2026-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_checkinrecord_flag_reason_checkinrecord_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='flag_reason',
            field=models.CharField(blank=True, choices=[('OFFLINE_RECORD', 'Offline record pending review'), ('MANUAL_FLAG', 'Manually flagged by admin')], max_length=100),
        ),
    ]
