# Generated by Django 6.0.5 on 2026-05-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erpnext_doc_name', models.CharField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='GeofenceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_metres', models.IntegerField()),
                ('wifi_ssid', models.CharField(blank=True, max_length=255)),
                ('wifi_bssid', models.CharField(blank=True, max_length=17)),
                ('rssi_threshold', models.IntegerField(default=-70)),
                ('enforce_5ghz', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_sites', to='companies.company')),
            ],
            options={
                'db_table': 'geofence_sites',
            },
        ),
    ]
