# Generated by Django 6.0.5 on 2026-05-18 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated'), ('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('checkin_received', 'Checkin Received')], max_length=32)),
                ('erpnext_doctype', models.CharField(max_length=64)),
                ('erpnext_doc_name', models.CharField(max_length=140)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='companies.company')),
            ],
            options={
                'db_table': 'webhook_events',
            },
        ),
    ]
