# Generated by Django 6.0.5 on 2026-05-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biometric_result', models.BooleanField(default=False)),
                ('geofence_result', models.BooleanField(default=False)),
                ('rssi_result', models.BooleanField(default=False)),
                ('antispoofing_result', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=True)),
                ('two_factor_only', models.BooleanField(default=False)),
                ('error_code', models.CharField(choices=[('SUCCESS', 'Success'), ('DEVICE_NOT_REGISTERED', 'Device Not Registered'), ('MOCK_LOCATION_DETECTED', 'Mock Location Detected'), ('ROOTED_DEVICE_DETECTED', 'Rooted Device Detected'), ('TIMESTAMP_IMPLAUSIBLE', 'Timestamp Implausible'), ('GEOFENCE_FAILED', 'Geofence Failed'), ('BIOMETRIC_FAILED', 'Biometric Failed'), ('WIFI_RSSI_BELOW_THRESHOLD', 'Wi-Fi RSSI Below Threshold'), ('ALREADY_CHECKED_IN', 'Already Checked In'), ('ALREADY_SYNCED', 'Already Synced')], default='SUCCESS', max_length=40)),
                ('final_decision', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('TWO_FACTOR_ONLY', 'Two Factor Only')], max_length=16)),
                ('gps_timestamp_used', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('checkin_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='checkins.checkinrecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='employees.employee')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
