# Generated by Django 6.0.5 on 2026-05-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('checkins', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['employee', 'created_at'], name='audit_logs_employe_b5bd3a_idx'),
        ),
    ]
