# Generated by Django 6.0.5 on 2026-06-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'get_latest_by': 'changed_at', 'verbose_name': 'Employee Status', 'verbose_name_plural': 'Employee Statuses'},
        ),
    ]
